default:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
  provider: Open AI
  model: DaVinci 3
  include_data_files: TRUE
  include_data_frames: TRUE
  include_doc_contents: FALSE
  system_msg: You are a helpful coding assistant
  model_arguments:
    temperature: 0.01
    max_tokens: 1000
    stream: TRUE
notebook:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
    For code output, use RMarkdown code chunks
    Include alt text code chunk option for all plots
chat:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
console:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
    For any line that is not code, prefix it with a: #
