default:
  prompt: |
    {tc_base_prompt}
  provider: Open AI
  model: DaVinci 3
  include_data_files: TRUE
  include_data_frames: TRUE
  include_doc_contents: FALSE
  system_msg: You are a helpful coding assistant
  model_arguments:
    temperature: 0.01
    max_tokens: 1000
    stream: TRUE
notebook:
  prompt: |
    {tc_base_prompt}
    For code output, use RMarkdown code chunks
    Include alt text code chunk option for all plots
chat:
  prompt: |
    {tc_base_prompt}
    For code output, use markdown code chunks
console:
  prompt: |
    {tc_base_prompt}
    For any line that is not code, prefix it with a: #
