default:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
  provider: Open AI
  model: GPT 3.5 Turbo
  include_data_files: TRUE
  include_data_frames: TRUE
  include_doc_contents: FALSE
  include_history: TRUE
  system_msg: You are a helpful coding assistant
  model_arguments:
    temperature: 0.01
    max_tokens: 1000
    stream: TRUE
notebook:
  prompt: |
    For code output, use RMarkdown code chunks
    Include alt text code chunk option for all plots
    Include eval=FALSE for ALL code chunks
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}

chat:
  prompt: |
    For code output, use RMarkdown code chunks
    Include alt text code chunk option for all plots
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
console:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
