default:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
  provider: Open AI
  model: GPT 3.5 Turbo
  include_data_files: TRUE
  include_data_frames: TRUE
  include_doc_contents: FALSE
  include_history: TRUE
  system_msg: You are a helpful coding assistant
  model_arguments:
    temperature: 0.01
    max_tokens: 1000
    stream: TRUE
chat:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
    For code output, use RMarkdown code chunks
    Avoid all code chunk options
script:
  prompt: |
    {readLines(system.file('prompt/base.txt', package = 'tidychat'))}
    Prefix ALL explanations with a pound sign
    Keep each line of explanations to no more than 80 characters
    DO NOT use Markdown for the code
